format: isaac_grasp
format_version: 1.0

object_frame_link: /World/mug
gripper_frame_link: /World/panda_hand

grasps:
  grasp_0:
      confidence: 1.0
      position: [-0.04346, 0.06759, 0.19895]
      orientation: {w: 0.00332, xyz: [0.98453, 0.16837, 0.04837]}
      cspace_position:
        panda_finger_joint1: 0.00943 # gripper closed
      pregrasp_cspace_position:
        panda_finger_joint1: 0.04 # gripper open
  grasp_1:
      confidence: 0.74
      position: [-0.04346, 0.06759, 0.19895]
      orientation: {w: 0.00332, xyz: [0.98453, 0.16837, 0.04837]}
      cspace_position:
        panda_finger_joint1: 0.00943
      pregrasp_cspace_position:
        panda_finger_joint1: 0.04
